version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

# Build documentation in the directory with Sphinx
sphinx:
  configuration: conf.py

python:
  install:
    - requirements: requirements.txt
